# Generated by Django 4.0.4 on 2022-10-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futurelabs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsdetails',
            name='shipping_speed',
        ),
    ]
