# Generated by Django 4.0.4 on 2022-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurelabs', '0002_remove_productsdetails_shipping_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdetails',
            name='product_name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='productsdetails',
            name='url',
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
    ]
